name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.5
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth_platform_interface: ^7.1.8
  firebase_core_platform_interface: ^5.0.0
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.8
