// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPYpgO6xUOh-F4IWVm6oWNmIhG0J3g10o',
    appId: '1:941175155785:web:14bd100a818c825cdaa398',
    messagingSenderId: '941175155785',
    projectId: 'flutterfirebaselogin-279ce',
    authDomain: 'flutterfirebaselogin-279ce.firebaseapp.com',
    storageBucket: 'flutterfirebaselogin-279ce.appspot.com',
    measurementId: 'G-FCREXG1ZMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_R7zwVvmA9162yf99i3jSa65DwMx49Xk',
    appId: '1:941175155785:android:70e61b6b7343942adaa398',
    messagingSenderId: '941175155785',
    projectId: 'flutterfirebaselogin-279ce',
    storageBucket: 'flutterfirebaselogin-279ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Mp8NViKgXxwBNfHPYMR-By-rzhwHgp0',
    appId: '1:941175155785:ios:17d30c92b598669edaa398',
    messagingSenderId: '941175155785',
    projectId: 'flutterfirebaselogin-279ce',
    storageBucket: 'flutterfirebaselogin-279ce.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Mp8NViKgXxwBNfHPYMR-By-rzhwHgp0',
    appId: '1:941175155785:ios:e25d626204154470daa398',
    messagingSenderId: '941175155785',
    projectId: 'flutterfirebaselogin-279ce',
    storageBucket: 'flutterfirebaselogin-279ce.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseLogin.RunnerTests',
  );
}
